typography_spectrum: 0.0888400673866272
content_rating:
  adult: false
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.9471079055219889
  lightness: 0.19737722328864038
  saturation: 0.8856010583695024
  rhythmicContrast: 0.23477882985025644
opengraph:
  type: ''
  appId: ''
  image: null
layout_spectrum: 0.8067093635909259
analytics: {}
author:
  name: Mathew Trojanowski
  url: ''
  email: mathewtrojanowski@live.com
logo: null
name: Mathew Trojanowski
cta: {}
favicon: null
title: 'Science, Tech, Games, Food'
purpose: []
