typography_spectrum: 0.2737515652552247
content_rating:
  adult: false
color:
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  brandStrength: 0.4598126350902021
  lightness: 0.3772141020745039
  saturation: 0.26831840141676366
  rhythmicContrast: 0.7429358691442758
opengraph:
  type: ''
  appId: ''
  image: null
layout_spectrum: 0.458704678574577
analytics: {}
author:
  name: Mathew Trojanowski
  url: ''
  email: mathewtrojanowski@live.com
logo: null
name: Mathew Trojanowski
cta: {}
favicon: null
title: ''
purpose: []
