name: Mathew Trojanowski
layout_spectrum: 0.8067093635909259
typography_spectrum: 0.0888400673866272
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.9471079055219889
  lightness: 0.19737722328864038
  saturation: 0.8856010583695024
  rhythmicContrast: 0.23477882985025644
purpose: []
title: 'Science,Tech,Games,Food'
author:
  name: Mathew Trojanowski
  url: ''
  email: mathewtrojanowski@live.com
content_rating:
  adult: false
navigation:
  - name: SpaceX
    id: 14768630-8c0e-468f-a19e-bc544d479e91
    type: content
