name: Mathew Trojanowski
favicon: null
layout_spectrum: 1
typography_spectrum: 0.91888
title: 'Science,Tech,Games'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7696ad'
    - '#2f4a68'
    - '#110509'
    - '#e5e4e2'
    - '#e5b573'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
