typography_spectrum: 0.91888
color:
  brandColors:
    - '#7696ad'
    - '#2f4a68'
    - '#110509'
    - '#e5e4e2'
    - '#e5b573'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Mathew Trojanowski
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: SpaceX
    id: 14768630-8c0e-468f-a19e-bc544d479e91
    type: content
favicon: null
title: 'Science,Tech,Games'
purpose: []
